compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - .yarn/plugins/plugin-setup-editor.cjs
  - .yarn/plugins/plugin-run-patch-package.cjs

yarnPath: .yarn/releases/yarn-4.7.0.cjs
